
export function generatePostgreSQL(project) {
  const lines = [];
  lines.push(`-- Generated by dbDraw for PostgreSQL`);
  lines.push(`-- Project: ${project.title}`);
  lines.push(`-- Created on: ${new Date().toISOString()}\n`);
  lines.push(`-- Enable UUID extension if required`);
  lines.push(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n`);

  // Create schemas if different from public
  const customSchemas = new Set();
  project.tables.forEach((t) => {
    if (t.schema && t.schema !== "public") {
      customSchemas.add(t.schema);
    }
  });
  customSchemas.forEach((s) => {
    lines.push(`CREATE SCHEMA IF NOT EXISTS "${s}";`);
  });
  if (customSchemas.size > 0) lines.push("");

  // Create tables
  for (const table of project.tables) {
    const qualifiedName = table.schema && table.schema !== "public" ? `"${table.schema}"."${table.name}"` : `"${table.name}"`;
    lines.push(`-- Table: ${table.name}${table.comment ? ` (${table.comment})` : ""}`);
    lines.push(`CREATE TABLE ${qualifiedName} (`);

    const colDefs = [];
    const pkCols = [];

    for (const col of table.columns) {
      let def = `  "${col.name}" ${col.type}`;
      if (!col.isNullable) def += ` NOT NULL`;
      if (col.isUnique && !col.isPk) def += ` UNIQUE`;
      if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
      colDefs.push(def);

      if (col.isPk) {
        pkCols.push(`"${col.name}"`);
      }
    }

    if (pkCols.length > 0) {
      colDefs.push(`  PRIMARY KEY (${pkCols.join(", ")})`);
    }

    lines.push(colDefs.join(",\n"));
    lines.push(`);\n`);

    if (table.comment) {
      lines.push(`COMMENT ON TABLE ${qualifiedName} IS '${table.comment.replace(/'/g, "''")}';\n`);
    }
  }

  // Add Foreign Key Constraints & Indexes
  if (project.relationships.length > 0) {
    lines.push(`-- Foreign Key Constraints & Referential Integrity`);
    for (const rel of project.relationships) {
      const sourceTable = project.tables.find((t) => t.id === rel.sourceTableId);
      const targetTable = project.tables.find((t) => t.id === rel.targetTableId);

      if (sourceTable && targetTable) {
        const constraintName = `fk_${sourceTable.name}_${rel.sourceColumnName}`;
        const sourceName = sourceTable.schema && sourceTable.schema !== "public" ? `"${sourceTable.schema}"."${sourceTable.name}"` : `"${sourceTable.name}"`;
        const targetName = targetTable.schema && targetTable.schema !== "public" ? `"${targetTable.schema}"."${targetTable.name}"` : `"${targetTable.name}"`;
        const onDelete = rel.onDelete || "CASCADE";

        lines.push(`ALTER TABLE ${sourceName}`);
        lines.push(`  ADD CONSTRAINT "${constraintName}"`);
        lines.push(`  FOREIGN KEY ("${rel.sourceColumnName}") REFERENCES ${targetName}("${rel.targetColumnName}")`);
        lines.push(`  ON DELETE ${onDelete};\n`);

        lines.push(`CREATE INDEX IF NOT EXISTS "idx_${sourceTable.name}_${rel.sourceColumnName}" ON ${sourceName} ("${rel.sourceColumnName}");\n`);
      }
    }
  }

  return lines.join("\n");
}

export function generateMySQL(project) {
  const lines = [];
  lines.push(`-- Generated by dbDraw for MySQL`);
  lines.push(`-- Project: ${project.title}\n`);

  for (const table of project.tables) {
    lines.push(`CREATE TABLE \`${table.name}\` (`);
    const colDefs = [];
    const pkCols = [];

    for (const col of table.columns) {
      let mySqlType = col.type;
      if (mySqlType.toUpperCase() === "UUID") mySqlType = "VARCHAR(36)";
      if (mySqlType.toUpperCase() === "SERIAL" || mySqlType.toUpperCase() === "BIGSERIAL") {
        mySqlType = mySqlType.toUpperCase() === "BIGSERIAL" ? "BIGINT UNSIGNED AUTO_INCREMENT" : "INT UNSIGNED AUTO_INCREMENT";
      }
      if (mySqlType.toUpperCase() === "JSONB") mySqlType = "JSON";

      let def = `  \`${col.name}\` ${mySqlType}`;
      if (!col.isNullable) def += ` NOT NULL`;
      if (col.isUnique && !col.isPk) def += ` UNIQUE`;
      if (col.defaultValue && !mySqlType.includes("AUTO_INCREMENT")) def += ` DEFAULT ${col.defaultValue}`;
      colDefs.push(def);

      if (col.isPk) {
        pkCols.push(`\`${col.name}\``);
      }
    }

    if (pkCols.length > 0) {
      colDefs.push(`  PRIMARY KEY (${pkCols.join(", ")})`);
    }

    lines.push(colDefs.join(",\n"));
    lines.push(`) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n`);
  }

  // Foreign keys
  for (const rel of project.relationships) {
    const sourceTable = project.tables.find((t) => t.id === rel.sourceTableId);
    const targetTable = project.tables.find((t) => t.id === rel.targetTableId);
    if (sourceTable && targetTable) {
      const constraintName = `fk_${sourceTable.name}_${rel.sourceColumnName}`;
      lines.push(`ALTER TABLE \`${sourceTable.name}\``);
      lines.push(`  ADD CONSTRAINT \`${constraintName}\``);
      lines.push(`  FOREIGN KEY (\`${rel.sourceColumnName}\`) REFERENCES \`${targetTable.name}\`(\`${rel.targetColumnName}\`)`);
      lines.push(`  ON DELETE ${rel.onDelete || "CASCADE"};\n`);
    }
  }

  return lines.join("\n");
}

export function generateSQLite(project) {
  const lines = [];
  lines.push(`-- Generated by dbDraw for SQLite`);
  lines.push(`-- Project: ${project.title}\n`);
  lines.push(`PRAGMA foreign_keys = ON;\n`);

  for (const table of project.tables) {
    lines.push(`CREATE TABLE IF NOT EXISTS "${table.name}" (`);
    const colDefs = [];
    const pkCols = [];

    for (const col of table.columns) {
      let sqType = "TEXT";
      const t = col.type.toUpperCase();
      if (t.includes("INT") || t.includes("SERIAL")) sqType = "INTEGER";
      else if (t.includes("DECIMAL") || t.includes("FLOAT") || t.includes("DOUBLE")) sqType = "REAL";
      else if (t.includes("BLOB")) sqType = "BLOB";
      else sqType = "TEXT";

      let def = `  "${col.name}" ${sqType}`;
      if (col.isPk && (col.type.toUpperCase() === "SERIAL" || col.type.toUpperCase() === "INTEGER")) {
        def += ` PRIMARY KEY AUTOINCREMENT`;
      } else {
        if (!col.isNullable) def += ` NOT NULL`;
        if (col.isUnique && !col.isPk) def += ` UNIQUE`;
        if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
        if (col.isPk) pkCols.push(`"${col.name}"`);
      }
      colDefs.push(def);
    }

    if (pkCols.length > 0 && !colDefs.some((c) => c.includes("PRIMARY KEY AUTOINCREMENT"))) {
      colDefs.push(`  PRIMARY KEY (${pkCols.join(", ")})`);
    }

    // SQLite inline foreign keys
    const tableRels = project.relationships.filter((r) => r.sourceTableId === table.id);
    for (const rel of tableRels) {
      const targetTable = project.tables.find((t) => t.id === rel.targetTableId);
      if (targetTable) {
        colDefs.push(`  FOREIGN KEY ("${rel.sourceColumnName}") REFERENCES "${targetTable.name}"("${rel.targetColumnName}") ON DELETE ${rel.onDelete || "CASCADE"}`);
      }
    }

    lines.push(colDefs.join(",\n"));
    lines.push(`);\n`);
  }

  return lines.join("\n");
}

export function generatePrisma(project) {
  const lines = [];
  lines.push(`// Generated by dbDraw for Prisma ORM`);
  lines.push(`// Project: ${project.title}\n`);
  lines.push(`datasource db {`);
  lines.push(`  provider = "postgresql"`);
  lines.push(`  url      = env("DATABASE_URL")`);
  lines.push(`}\n`);
  lines.push(`generator client {`);
  lines.push(`  provider = "prisma-client-js"`);
  lines.push(`}\n`);

  for (const table of project.tables) {
    const modelName = table.name.charAt(0).toUpperCase() + table.name.slice(1).replace(/_([a-z])/g, (_, l) => l.toUpperCase());
    lines.push(`model ${modelName} {`);

    for (const col of table.columns) {
      let prismaType = "String";
      const u = col.type.toUpperCase();
      if (u.includes("INT") || u.includes("SERIAL")) prismaType = "Int";
      else if (u.includes("DECIMAL") || u.includes("FLOAT") || u.includes("NUMERIC")) prismaType = "Float";
      else if (u.includes("BOOL")) prismaType = "Boolean";
      else if (u.includes("TIMESTAMP") || u.includes("DATE")) prismaType = "DateTime";
      else if (u.includes("JSON")) prismaType = "Json";

      if (col.isNullable) prismaType += "?";

      let attrs = "";
      if (col.isPk) {
        attrs += " @id";
        if (u.includes("SERIAL")) attrs += " @default(autoincrement())";
        else if (u === "UUID") attrs += " @default(uuid())";
      } else {
        if (col.isUnique) attrs += " @unique";
        if (u.includes("TIMESTAMP") && (col.name.includes("created") || col.name === "created_at")) {
          attrs += " @default(now())";
        }
      }

      lines.push(`  ${col.name.padEnd(20)} ${prismaType.padEnd(10)}${attrs}`);
    }

    // Relations out
    const outgoingRels = project.relationships.filter((r) => r.sourceTableId === table.id);
    for (const rel of outgoingRels) {
      const targetTable = project.tables.find((t) => t.id === rel.targetTableId);
      if (targetTable) {
        const targetModel = targetTable.name.charAt(0).toUpperCase() + targetTable.name.slice(1).replace(/_([a-z])/g, (_, l) => l.toUpperCase());
        const relationFieldName = targetTable.name.toLowerCase();
        lines.push(`  ${relationFieldName.padEnd(20)} ${targetModel.padEnd(10)} @relation(fields: [${rel.sourceColumnName}], references: [${rel.targetColumnName}])`);
      }
    }

    // Relations in
    const incomingRels = project.relationships.filter((r) => r.targetTableId === table.id);
    for (const rel of incomingRels) {
      const sourceTable = project.tables.find((t) => t.id === rel.sourceTableId);
      if (sourceTable) {
        const sourceModel = sourceTable.name.charAt(0).toUpperCase() + sourceTable.name.slice(1).replace(/_([a-z])/g, (_, l) => l.toUpperCase());
        const fieldName = sourceTable.name.toLowerCase() + "s";
        lines.push(`  ${fieldName.padEnd(20)} ${sourceModel}[]`);
      }
    }

    lines.push(`  @@map("${table.name}")`);
    lines.push(`}\n`);
  }

  return lines.join("\n");
}

export function generateMongoose(project) {
  const lines = [];
  lines.push(`// Generated by dbDraw for MongoDB / Mongoose`);
  lines.push(`// Project: ${project.title}\n`);
  lines.push(`import mongoose, { Schema } from 'mongoose';\n`);

  for (const table of project.tables) {
    const modelName = table.name.charAt(0).toUpperCase() + table.name.slice(1).replace(/_([a-z])/g, (_, l) => l.toUpperCase());
    const schemaName = `${modelName}Schema`;

    lines.push(`const ${schemaName} = new Schema({`);
    for (const col of table.columns) {
      if (col.isPk && col.name === "id") continue;

      let mgType = "String";
      const u = col.type.toUpperCase();
      if (u.includes("INT") || u.includes("DECIMAL") || u.includes("FLOAT")) mgType = "Number";
      else if (u.includes("BOOL")) mgType = "Boolean";
      else if (u.includes("TIMESTAMP") || u.includes("DATE")) mgType = "Date";
      else if (u.includes("JSON")) mgType = "Schema.Types.Mixed";

      const rel = project.relationships.find((r) => r.sourceTableId === table.id && r.sourceColumnName === col.name);
      if (rel) {
        const targetTable = project.tables.find((t) => t.id === rel.targetTableId);
        const refName = targetTable ? targetTable.name.charAt(0).toUpperCase() + targetTable.name.slice(1) : "Ref";
        lines.push(`  ${col.name}: { type: Schema.Types.ObjectId, ref: '${refName}'${!col.isNullable ? ", required: true" : ""} },`);
      } else {
        const required = !col.isNullable ? ", required: true" : "";
        const unique = col.isUnique ? ", unique: true" : "";
        lines.push(`  ${col.name}: { type: ${mgType}${required}${unique} },`);
      }
    }
    lines.push(`}, { timestamps: true });\n`);

    lines.push(`export const ${modelName} = mongoose.models.${modelName} || mongoose.model('${modelName}', ${schemaName});\n`);
  }

  return lines.join("\n");
}

export function generateTypeScript(project) {
  const lines = [];
  lines.push(`// Generated Model Definitions by dbDraw`);
  lines.push(`// Project: ${project.title}\n`);

  for (const table of project.tables) {
    const interfaceName = table.name.charAt(0).toUpperCase() + table.name.slice(1).replace(/_([a-z])/g, (_, l) => l.toUpperCase());
    lines.push(`export interface ${interfaceName} {`);

    for (const col of table.columns) {
      let tsType = "string";
      const u = col.type.toUpperCase();
      if (u.includes("INT") || u.includes("SERIAL") || u.includes("DECIMAL") || u.includes("FLOAT")) tsType = "number";
      else if (u.includes("BOOL")) tsType = "boolean";
      else if (u.includes("TIMESTAMP") || u.includes("DATE")) tsType = "string | Date";
      else if (u.includes("JSON")) tsType = "Record<string, unknown>";

      const optional = col.isNullable ? "?" : "";
      lines.push(`  ${col.name}${optional}: ${tsType};`);
    }

    lines.push(`}\n`);
  }

  return lines.join("\n");
}
